### PR TITLE
Bug/stack rm container names and restart policy

### PR DESCRIPTION
**Pull request by simonhir**
**Description**

- Rm container names to prevent naming collision with refarch-templates on startup.
- Rm restart policy to prevent auto startup

**Reference**

Issue https://github.com/it-at-m/refarch-templates/issues/309

### CODE REVIEW

**Review by devtobi — COMMENTED** [review]
Don't understand why it is colliding when using different stack names.

**Comment by devtobi** [comment]
Does this PR relate to any issue? If yes, please link it.

**Comment by simonhir** [comment]
> Don't understand why it is colliding when using different stack names.

You can i try it out, it just is that way.
In my opinion that's because docker just runs each docker-compose container also as normal container, and therefore pinned container names can collide. Also i see absolutely no advantage in doing this.

**Comment by devtobi** [comment]
> In my opinion that's because docker just runs each docker-compose container also as normal container, and therefore pinned container names can collide. Also i see absolutely no advantage in doing this.

But does this mean a completely new set of containers with new volumes is created everytime I start up the stack? This would bloat the local machine, right? If not using named containers, maybe we should use named volumes to only store data once (of course separate to refarch-templates stack)?

**Comment by simonhir** [comment]
> But does this mean a completely new set of containers with new volumes is created everytime I start up the stack?

No this just fixes the collisions and the containers get a number suffix

**Comment by devtobi** [comment]
> > But does this mean a completely new set of containers with new volumes is created everytime I start up the stack?
> 
> No this just fixes the collisions and the containers get a number suffix

Ok as long this suffix is static and does not auto increment thats fine for me. Other solution would be to just rename the container names for this scenario, right?

**Comment by simonhir** [comment]
> Other solution would be to just rename the container names for this scenario, right?

Yes but why working around a feature docker-compose brings by default. I think defining the name is just bad practice if not explicitly needed for something, even if i don't know what that could be.

**Comment by devtobi** [comment]
> > Other solution would be to just rename the container names for this scenario, right?
> 
> Yes but why working around a feature docker-compose brings by default. I think defining the name is just bad practice if not explicitly needed for something, even if i don't know what that could be.

So that would mean this change would be relevant to github.com/it-at-m/refarch-templates as well, right? Please open a PR there too. :)

**Comment by simonhir** [comment]
https://github.com/it-at-m/refarch-templates/pull/397

**Review by devtobi — APPROVED** [review]
LGTM

**Pull request merged**
