### PR TITLE
:bug: fix reactive tracing

### LINKED ISSUE #25: TraceId and SpanId not shown in log
**Is your feature request related to a problem? Please describe.**
TraceId and SpanId are not shown in log output.

**Describe the solution you'd like**
TraceId and SpanId should be logged in the output

**Solution**
`Hooks.enableAutomaticContextPropagation();` has to be called
See https://medium.com/@aakashkumar2001jha/mastering-reactive-tracing-in-spring-boot-3-a-comprehensive-guide-to-achieving-seamless-29c1229177ca for a more detailed example.
It might be necessary to add additional dependencies and bean implementations (see provided link)

**Describe alternatives you've considered**

**Additional context**
Take a further look into https://medium.com/@aakashkumar2001jha/mastering-reactive-tracing-in-spring-boot-3-a-comprehensive-guide-to-achieving-seamless-29c1229177ca for more sophisticated setup.
- Internal issue: https://git.muenchen.de/ccse/refarch-archetype/refarch-archetype-apigateway/-/issues/118

### PR DESCRIPTION
**Pull request by simonhir**
**Description**

Fix reactive tracing.

**Reference**

Issues closes #25

### CODE REVIEW

**Comment by devtobi** [comment]
Did you take a look at the best practices mentioned in https://medium.com/@aakashkumar2001jha/mastering-reactive-tracing-in-spring-boot-3-a-comprehensive-guide-to-achieving-seamless-29c1229177ca? Are those applicable to our case?

**Review by devtobi — COMMENTED** [review]
Did you take a look at the best practices mentioned in https://medium.com/@aakashkumar2001jha/mastering-reactive-tracing-in-spring-boot-3-a-comprehensive-guide-to-achieving-seamless-29c1229177ca? Are those applicable to our case?

**Comment by simonhir** [comment]
> Did you take a look at the best practices mentioned in https://medium.com/@aakashkumar2001jha/mastering-reactive-tracing-in-spring-boot-3-a-comprehensive-guide-to-achieving-seamless-29c1229177ca? Are those applicable to our case?

As far as i understood it they are only for logging and there is nor real benefit for us. But feel free to look over it again maybe you'll see it differently

**Review by devtobi — APPROVED** [review]
LGTM

**Pull request merged**
